### ISSUE TITLE
Add support for cycle renaming

### ISSUE THREAD

**Issue by sudo-nice** [dmulholl/vimv#1]
I realize, this feature might complicate the implementation, but you also might find it interesting.

1. Open two files: `vimv a b`.
2. Exchange the file's names, so `a` becomes `b` and `b` becomes `a`.
3. Save and exit.
What happens: `Error: the output file 'b' already exists, use --force to overwrite`.
Suggestion: actually, rename the files.

I know, [this] renamer (written in Go) supports it.

[this]: https://github.com/itchyny/mmv

**Comment by dmulholl** [comment]
You're right, that is an interesting feature :) 

I'll add it over the next couple of days and bump this thread when I release the updated version. Thanks for the idea, I hadn't thought of it before, but now that you bring it up it's definitely something I want to support.

**Comment by dmulholl** [comment]
I just released version 1.2.0 which adds support for cycle renaming. I'm going to close this issue but feel free to reopen it if you find any bugs.

Thanks for the suggestion!

**Comment by sudo-nice** [comment]
Works like a charm, thank you for the feature! `vimv` is my main renamer from now on. :smile:
