### ISSUE TITLE
Support to use git mv as an option?

### ISSUE THREAD

**Issue by xaljer** [dmulholl/vimv#2]
Using `git mv` and `git mv --dry-run` if specified?

**Comment by dmulholl** [comment]
Good idea. I've added support in `1.4.0` for a `--git/-g` flag which will use `git mv` to rename files or `git rm` to delete files if they're being tracked by git. 

(I haven't added support for a `--dry-run` flag as I don't think it makes sense in the context of a visual tool.)

Thanks for the suggestion.

**Comment by meribold** [comment]
This feature was removed in version 2.0.0.
