### ISSUE TITLE
vimv cannot handle files containing certain unicode characters

### ISSUE THREAD

**Issue by MinmoTech** [dmulholl/vimv#7]
I have the following file: `　-SsV0tZMUCNE.webm` (unicode representation is `\343\200\200-SsV0tZMUCNE.webm`) which vimv cannot open.

I get the following error:
```bash
vimv "　-SsV0tZMUCNE.webm"
Error: the input file '-SsV0tZMUCNE.webm' does not exist.
```

**Comment by dmulholl** [comment]
Thanks, fixed in `v1.8.0`.
